### ISSUE TITLE
[Bug] - Amazon Corretto-11.0.16.8.2 referencing non existent graphics library (libjpeg.so.62)

### ISSUE THREAD

**Issue by cst-cfalling** [amazonlinux/amazon-linux-2022#171]
**Describe the bug**

We are using PDFBox in a Java application running on Amazon Corretto.   Previous version ( 5.15.25-14.106.amzn2022.x86_64 ) of Amazon linux 2022 used OpenJDK build but latest versions have replaced this with Corretto.   Also prior version of AL 2022 included /usr/lib64/libjpeg.so.62 

```
[ec2-user@ip-172-20-25-81 lib]$ uname -r
5.15.25-14.106.amzn2022.x86_64

[ec2-user@ip-172-20-25-81 lib]$ ls -la /usr/lib64/libjpeg.so.62
lrwxrwxrwx. 1 root root 17 Oct 21  2021 /usr/lib64/libjpeg.so.62 -> libjpeg.so.62.3.0

[ec2-user@ip-172-20-25-81 lib]$ java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)
[ec2-user@ip-172-20-25-81 lib]$
```

```
[root@eportal-cstdev-us ~]# uname -r
5.15.54-25.126.amzn2022.x86_64

[root@eportal-cstdev-us ~]# ls -l /usr/lib64/libjpeg.so.62
ls: cannot access '/usr/lib64/libjpeg.so.62': No such file or directory

[root@eportal-cstdev-us ~]# ls -l /usr/lib64/libturbojpeg.so.0
lrwxrwxrwx. 1 root root 21 Oct 21  2021 /usr/lib64/libturbojpeg.so.0 -> libturbojpeg.so.0.2.0

[root@eportal-cstdev-us ~]# java --version
openjdk 11.0.16 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-11.0.16.8.2 (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.8.2 (build 11.0.16+8-LTS, mixed mode)
```

Current version even with turbojpeg package installed does not contain this shared library, but the java desktop module is still attempting to load and use this capability.  

Exception in thread "pool-8-thread-1" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-amazon-corretto.x86_64/lib/libjavajpeg.so: libjpeg.so.62: cannot open shared object file: No such file or directory
    at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
    at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
    at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
    at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2651)
    at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
    at java.base/java.lang.System.loadLibrary(System.java:1873)
    at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter$1.run(JPEGImageWriter.java:181)
    at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter$1.run(JPEGImageWriter.java:179)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter.<clinit>(JPEGImageWriter.java:178)
    at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:100)
    at java.desktop/javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
    at java.desktop/javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:849)
    at java.desktop/javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:833)
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.getJPEGImageWriter(JPEGFactory.java:255)
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.encodeImageToJPEGStream(JPEGFactory.java:278)
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createJPEG(JPEGFactory.java:227)
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createFromImage(JPEGFactory.java:190)
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createFromImage(JPEGFactory.java:175)
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createFromImage(JPEGFactory.java:160)
    at com.cellsignal.erp.m3.server.printing.PaperPrinter.convertPDF4To1(PaperPrinter.java:227)
    at com.cellsignal.erp.m3.server.printing.PaperPrinter.storeNG(PaperPrinter.java:88)
    at com.cellsignal.erp.m3.server.printing.PaperPrintServiceImpl.print(PaperPrintServiceImpl.java:608)
    at com.cellsignal.erp.m3.server.printing.PaperPrintServiceImpl.print(PaperPrintServiceImpl.java:302)
    at com.cellsignal.packlabels.PrintBatchServiceImpl.printOrganizedByBatch(PrintBatchServiceImpl.java:318)

We would like to be able to either install the openjdk package or ensure that the libjpeg.so.62 shared library being looked for exists?

**To Reproduce**
1. Install corretto and turbojpeg
2.  Run a java program with PDFBox. that renders a PDF to a JPEG image and attempts to use that as an input to a object in a document.  Note I am working on providing a sample test program to attach to this issue.
3. We have attempted to run this with both normal and headless mode with no differences in behavior.

Key lines:  
   FileInputStream is = new FileInputStream(new File("foo.pdf"));
   PDDocument document = PDDocument.load(is);
   PDFRenderer renderer = new PDFRenderer(document);

   PDDocument documentNew = new PDDocument();

   BufferedImage bi = renderer.renderImage (0, 2.0f);
   PDImageXObject pdImage = JPEGFactory.createFromImage(documentNew, bi);

**Expected behavior**
Native Shared library being loaded by Java module exists and successfully loaded

**Additional context**

**Comment by cst-cfalling** [comment]
[PdfChecker-test.zip](https://github.com/amazonlinux/amazon-linux-2022/files/9429332/PdfChecker-test.zip)
Example test code which takes a PDF file as an argument and uses PDFBox to resize the first page and add it as an image to a  new document.  This exhibits the bug as described due to the missing native library.

**Comment by stewartsmith** [comment]
Thanks for the detail and reproducer! We've managed to reproduce and someone is looking into it.

**Comment by lutkerd** [comment]
Hello,
I'm on the Corretto team, can you tell me which of the Corretto packages you have installed? We have both headless and headful packages and the libjpeg requirement is on the headful or main package. I suspect you just have the headless package installed and installing `java-11-amazon-corretto` will resolve your issue. We will fix this on our end and move the requires to the headless package and get it out in our next release in October.

```
# rpm -qa |grep corretto
java-11-amazon-corretto-11.0.16+9-1.amzn2.x86_64
java-11-amazon-corretto-headless-11.0.16+9-1.amzn2.x86_64
```

**Comment by cst-cfalling** [comment]
@lutkerd Thank you for the information, I was able to confirm that we can replace the default headless versions (based on installing dnf install java-11-amazon-corretto-devel with ansible) with the full corretto version and that the graphics work as expected.   Thanks for letting us know that the dependency will be updated in a future release.

**Comment by Kemotaha** [comment]
Thanks for the confirmation.  I am going to close out this issue
